### ISSUE TITLE
gb28181-cpp 支持vs编译不？

### ISSUE THREAD

**Issue by zhanjx1314** [1461521844lijin/gb28181-CPP#3]
目前我将依赖的库文件都编译完成了。
主工程应该是一些头文件关联的问题导致编译大量错误。
不知道您是否在vs编译过，如果编译过能否指导下，谢谢。

**Comment by 1461521844lijin** [comment]
默认是在linux下运行的，readme中的三方库也是直接装在系统默认路径下
因此写的Cmakelist.txt都是直接查找的linux下的系统路径
不过项目所依赖的三方库都是支持win下编译的，所以你要是在win下编译得修改Cmakelist.txt中的引用和链接路径，换成你本地三方库路径

建议还是换linux系统上，就能按照readme运行

**Comment by zhanjx1314** [comment]
Linux 下问题不大，哈哈哈。
我也是刚刚看到这个项目，win 上主要是ide 好用。我看看基础库都可以编过去于是想试试。
