### ISSUE TITLE
使用过程中发现了一些问题

### ISSUE THREAD

**Issue by Washington-DC** [1461521844lijin/gb28181-CPP#5]
1、对于设备通道ID和设备ID不一致的无法点播，以及对于多个通道的设备存在同样的问题，这里应该使用通道ID去点播才对
2、对于云台控制校验码这里计算不正确，应该是 zoomSpeed << 4
3、对于md5这部分代码在osip里边已经有了
4、可以对on_stream_not_found和on_stream_none_reader进行处理，以实现按需拉流的功能

最后，对作者表示感谢

**Comment by 1461521844lijin** [comment]
1、我本地测试时不同设备id和通道id是能正确点播的，不过确实没有考虑到多个通道设备的情况，这里之后会修改，多谢提醒
2、位移和取或操作是等价的
3、这部分多余代码我后面移除
4、开始的设计里面是想屏蔽用户对流媒体服务的感知（因为打算做多zlm节点的负载均衡），所以没有实现on_stream_not_found，点播都要先经过信令服务，虽然这样是会延迟画面打开的速度，不过也算按需拉流吧

**Comment by Washington-DC** [comment]
我觉得这里的等价与否 可以测试一下,for example:  zoomSpeed=1

**Comment by 1461521844lijin** [comment]
确实不等价，不过我测过了 写<<和&都能正确控制相机变倍
似乎相机根本关心这个校验参数一样

**Comment by Washington-DC** [comment]
好吧，我这里测试发现相机没有任何响应才发现的这个问题

**Comment by Washington-DC** [comment]
还是对作者表示感谢哈，在此项目改进实现了wvp的功能
