### ISSUE TITLE
make编译时报错

### ISSUE THREAD

**Issue by qc824676623** [1461521844lijin/gb28181-CPP#7]
![d06cda7c08b11b94d1bc119941e747c](https://github.com/1461521844lijin/gb28181-CPP/assets/46586994/e0f9a135-207a-4803-a047-261608ea07f1)
总提示GETWAY错误，是我少下了什么库嘛？我是按照安装步骤来的

**Comment by 1461521844lijin** [comment]
命名空间嵌套的用法c++17才支持，请确保你的编译器支持并开启C++17
否则可以将namespace DTD::GETWAY {}  修改为 
namespace DTD
{
namespace GETWAY
{

}
}

**Comment by qc824676623** [comment]
![image](https://github.com/1461521844lijin/gb28181-CPP/assets/46586994/24846579-27b9-4f7b-9a63-4eb9fc7d03ea)
gb28181-CPP/build/目录下make失败，应该是与openssl链接有问题。
1.检查了usr/local/lib/libeXosip2.so文件已存在。
2.尝试升级openssl至1.1.1h，也不行。
请问作者用的是哪个版本openssl,我这怎么总失败555

**Comment by qc824676623** [comment]
经过反复检查
1.检查本机openssl链接问题 ，确实有问题（cmakelists中设置openssl路径或者检查下安装openssl时的路径、软连接等）。之后发现仍有一个函数报错undefined
2.此时用的openssl 1.1.1，发现exosip工具编译时SSL_get_peer_temp_key（xx,xx）（与openssl有关）函数报错。查看编译时warn信息发现SSL_get_peer_temp_key（xx,xx）已弃用，根据建议替换该函数为SSL_get_sever_temp_key（xx,xx）即可
可以用了，感谢作者Thanks♪(･ω･)ﾉ
